# The name of the project (required) is used for displaying purposes within IO environments and IDEs.
name: elvan

# A list of paths to local packages that are included in the Melos workspace. Each entry can be a specific path or a glob pattern.
packages:
  - "apps/*"
  - "packages/**"

# Recommended option for projects with Dart 2.17.0 or greater.
#
# This enables a new mechanism for linking local packages, which integrates
# better with other tooling (e.g. dart tool, flutter tool, IDE plugins) than the
# mechanism currently being used by default. Please read the documentation for
# usePubspecOverrides before enabling this feature.
#
# See https://melos.invertase.dev/getting-started#setup
command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  
  pod_install:
    run: melos exec -- "pod install"
    description: Run `pod install` in all packages

  pub_get:
    run: melos exec -- "flutter pub get"
    description: Run `flutter pub get` in all packages

  build_runner:
    run: melos exec -- "dart run build_runner build -d"
    description: Run `dart run build_runner build -d` in all packages

  build_runner_watch:
    run: melos exec -- "dart run build_runner watch -d"
    description: Run `dart run build_runner watch -d` in all packages

  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages
  
  format:
    run: melos exec -- "flutter format . --set-exit-if-changed"
    description: Run `flutter format .` in all packages

  test:
    # Only run the test command when the package has a test directory
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run `flutter test` in all packages
