name: elvan_admin
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: '>=2.18.6 <3.7.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # shared libs
  elvan_shared:

  intl: ^0.18.0

  #Hooks, States
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  riverpod_annotation: ^2.1.1

  #Route
  auto_route: ^7.1.0

  # Code generator
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_screenutil: ^5.6.0

  #moment
  moment_dart: ^0.17.4

  #images
  flutter_svg: ^1.1.6

  #firebase
  firebase_core: ^2.2.0
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6

  #storage cache  
  shared_preferences: ^2.0.17
  motion_toast: ^2.6.4
  printing: ^5.9.3
  #flutterfire_ui: ^0.4.3+20
  collection: ^1.17.0
  just_audio: ^0.9.32


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  auto_route_generator: ^7.0.0
  riverpod_generator: ^2.2.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/audio/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

